// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dczbuuctrtcywndoyzfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjemJ1dWN0cnRjeXduZG95emZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzI3NzYsImV4cCI6MjA2OTMwODc3Nn0.K4Bwoxl9UTiNeLteTsrAWmJPexyaYyMy5FWu71JMUKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});